// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BatchCalculate(arg1:main.BatchCalculateParams):Promise<main.BatchCalculationResult>;

export function CalculateBulkRainbowPackCost(arg1:number):Promise<Record<string, any>>;

export function CalculateDrillAffordTime(arg1:string,arg2:string,arg3:number,arg4:number,arg5:Array<Record<string, any>>):Promise<main.DrillAffordResult>;

export function CalculateGasProfit(arg1:string,arg2:number,arg3:number):Promise<number>;

export function CalculateGoalTime(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<string>;

export function CalculatePacksNeeded99Confidence(arg1:number,arg2:number):Promise<number>;

export function CalculateProduction(arg1:number,arg2:number,arg3:number):Promise<main.CalculationResult>;

export function CheckForUpdates():Promise<Record<string, any>>;

export function FormatDuration(arg1:number):Promise<string>;

export function FormatLarge(arg1:number):Promise<string>;

export function GetAllDrills():Promise<Array<main.Drill>>;

export function GetAllRefineries():Promise<Array<main.Refinery>>;

export function GetAllWalls():Promise<Array<main.Wall>>;

export function GetConfig():Promise<main.Config>;

export function GetDrill(arg1:string):Promise<main.Drill>;

export function GetPackDrills(arg1:string):Promise<Array<main.PackDrill>>;

export function GetRefinery(arg1:string):Promise<main.Refinery>;

export function ParseLargeNumber(arg1:string):Promise<number>;

export function SaveConfig(arg1:main.Config):Promise<void>;

export function UpdateConfig(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;
