// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BatchCalculate(arg1) {
  return window['go']['main']['App']['BatchCalculate'](arg1);
}

export function CalculateBulkRainbowPackCost(arg1) {
  return window['go']['main']['App']['CalculateBulkRainbowPackCost'](arg1);
}

export function CalculateDrillAffordTime(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CalculateDrillAffordTime'](arg1, arg2, arg3, arg4, arg5);
}

export function CalculateGasProfit(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateGasProfit'](arg1, arg2, arg3);
}

export function CalculateGoalTime(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CalculateGoalTime'](arg1, arg2, arg3, arg4, arg5);
}

export function CalculatePacksNeeded99Confidence(arg1, arg2) {
  return window['go']['main']['App']['CalculatePacksNeeded99Confidence'](arg1, arg2);
}

export function CalculateProduction(arg1, arg2, arg3) {
  return window['go']['main']['App']['CalculateProduction'](arg1, arg2, arg3);
}

export function CheckForUpdates() {
  return window['go']['main']['App']['CheckForUpdates']();
}

export function FormatDuration(arg1) {
  return window['go']['main']['App']['FormatDuration'](arg1);
}

export function FormatLarge(arg1) {
  return window['go']['main']['App']['FormatLarge'](arg1);
}

export function GetAllDrills() {
  return window['go']['main']['App']['GetAllDrills']();
}

export function GetAllRefineries() {
  return window['go']['main']['App']['GetAllRefineries']();
}

export function GetAllWalls() {
  return window['go']['main']['App']['GetAllWalls']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDrill(arg1) {
  return window['go']['main']['App']['GetDrill'](arg1);
}

export function GetPackDrills(arg1) {
  return window['go']['main']['App']['GetPackDrills'](arg1);
}

export function GetRefinery(arg1) {
  return window['go']['main']['App']['GetRefinery'](arg1);
}

export function ParseLargeNumber(arg1) {
  return window['go']['main']['App']['ParseLargeNumber'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function UpdateConfig(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateConfig'](arg1, arg2, arg3, arg4);
}
