name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        mkdir -p builds
        $env:CGO_ENABLED = "1"
        go build -ldflags "-H windowsgui" -o builds/oilempire.exe .

    - name: Create Release Draft
      uses: softprops/action-gh-release@v1
      with:
        files: builds/oilempire.exe
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}